"use client";

import { useEffect, useRef, useState } from "react";
import dynamic from "next/dynamic";
import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { DRACOLoader } from "three/examples/jsm/loaders/DRACOLoader.js";
import stopsData from "@/scene/camera-stops.json";

/**
 * The 3D half of the services page: loads the diorama and flies a camera between
 * the five service zones as the pinned section is scrolled.
 *
 * Scroll position arrives through a ref rather than a prop. Driving a camera from
 * React state would re-render the tree on every frame of a 24-viewport scroll; the
 * ref lets the rAF loop read the latest value and touch nothing else.
 *
 * Camera stops are generated by scene/build_scene.py alongside the model, already
 * converted to three's Y-up axes. They are imported rather than fetched so a stop
 * that stops existing is a build error rather than a blank screen.
 *
 * Two things here can fail on a machine we do not control — the WebGL context and the
 * GLB — and either one used to leave the pinned section as 24 viewports of nothing.
 * Both hand over to the SVG board instead, which reads the same five zones off the
 * same active index.
 */

/* Lazy: the fallback is dead weight on every visit where WebGL works, which is nearly
   all of them. Splitting it out means it is fetched only once something has gone wrong. */
const ServicesScene = dynamic(() => import("./ServicesScene"), { ssr: false });

export type Stop = {
  id: string;
  position: [number, number, number];
  target: [number, number, number];
  anchor: [number, number, number];
  fov: number;
};

export const STOPS = stopsData.stops as Stop[];

/* Long holds with a short move between them — the reference dwells far longer than
   it travels, which is what gives the copy time to be read. */
const MOVE_FROM = 0.32;
const MOVE_TO = 0.86;

/* The path is traversed over the middle of the section, leaving a hold at each end.
   Without the tail the last zone reaches its stop exactly as the section runs out,
   so it got less than half the dwell of every other zone. */
const LEAD = 0.03;
const TAIL = 0.1;

const clamp01 = (v: number) => (v < 0 ? 0 : v > 1 ? 1 : v);
/* smootherstep: zero first and second derivative at both ends, so the camera
   settles into a stop instead of arriving with residual velocity */
const ease = (t: number) => t * t * t * (t * (t * 6 - 15) + 10);

/** Where the camera sits for a given scroll progress, as a curve parameter. */
export function stopParam(progress: number) {
  const span = STOPS.length - 1;
  const t = clamp01((clamp01(progress) - LEAD) / (1 - LEAD - TAIL)) * span;
  const i = Math.min(Math.floor(t), span - 1);
  const f = t - i;
  const moved = ease(clamp01((f - MOVE_FROM) / (MOVE_TO - MOVE_FROM)));
  return { u: (i + moved) / span, i, moved };
}

/** Scroll progress that parks the camera on a stop, a little past its arrival so
 *  the deep link lands mid-dwell rather than mid-flight. Inverse of stopParam. */
export function progressForStop(stopIndex: number) {
  const span = STOPS.length - 1;
  const t = Math.min(stopIndex + 0.15, span);
  return LEAD + (t / span) * (1 - LEAD - TAIL);
}

/** Which zone's copy should be on screen. -1 is the establishing shot. */
export function activeZone(progress: number) {
  const { i, moved } = stopParam(progress);
  // hand over at the midpoint of the move, so copy swaps while the camera is busy
  return (moved < 0.5 ? i : i + 1) - 1;
}

function vec(t: [number, number, number]) {
  return new THREE.Vector3(t[0], t[1], t[2]);
}

/* Pivots the rig drives, as they are named in the GLB. Kept in one place so the
   load-time check and the frame loop cannot disagree about what should exist. */
const ROOF = "anim_roof_ict";
const TURBINES = ["anim_turbine_hub_00", "anim_turbine_hub_01", "anim_turbine_hub_02"];
const PUMP = "anim_pump_beam";
const CRANE = "anim_crane_jib";
const ANIMATED_NODES = [ROOF, ...TURBINES, PUMP, CRANE];

/** How far the warehouse roof rises, in scene metres. */
const ROOF_LIFT = 90;

/* Indices into STOPS (0 is the establishing shot), not into ZONES. */
const STOP_ICT = 2;
const STOP_ENGINEERING = 3;
const STOP_ENERGY = 5;

/** 1 when the camera is parked on a stop, falling to 0 half a segment either side. */
function nearStop(u: number, stopIndex: number) {
  const span = STOPS.length - 1;
  return 1 - Math.min(Math.abs(u - stopIndex / span) / (0.5 / span), 1);
}

/** The board's paper colour — background, fog and the section behind it all share it. */
export const BOARD = "#f4f4f2";

/* Blender's sun directions, carried across to Y-up. Keeping the rig in step with the
   bake means a stop framed in Blender lights the same way in the browser. */
const SUNS: [string, number, [number, number, number]][] = [
  ["#fff7eb", 2.6, [0.426, 0.669, 0.609]],
  ["#e6edff", 1.1, [-0.723, 0.469, -0.506]],
  ["#fff2d1", 0.5, [0.167, 0.276, -0.947]],
];

export default function ServicesStage({
  progress,
  active,
}: {
  progress: React.MutableRefObject<number>;
  active: number;
}) {
  const mount = useRef<HTMLDivElement>(null);
  const activeRef = useRef(active);
  activeRef.current = active;
  const [fallback, setFallback] = useState(false);

  useEffect(() => {
    if (fallback) return;
    const host = mount.current;
    if (!host) return;

    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    let renderer: THREE.WebGLRenderer;
    try {
      renderer = new THREE.WebGLRenderer({
        antialias: true,
        powerPreference: "high-performance",
      });
    } catch {
      /* No context — blocked, disabled, or too many live contexts on the page. Nothing
         below this point can run, so give the section something to draw and stop. */
      setFallback(true);
      return;
    }
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    host.appendChild(renderer.domElement);
    renderer.domElement.style.display = "block";

    const scene = new THREE.Scene();
    scene.background = new THREE.Color(BOARD);
    /* the ground plane is deliberately enormous so its edge never shows; fog is what
       dissolves it into the page rather than letting it run to a visible horizon */
    scene.fog = new THREE.Fog(BOARD, 420, 1700);

    const camera = new THREE.PerspectiveCamera(40, 1, 1, 4000);

    for (const [color, intensity, dir] of SUNS) {
      const light = new THREE.DirectionalLight(new THREE.Color(color), intensity);
      light.position.set(dir[0] * 700, dir[1] * 700, dir[2] * 700);
      scene.add(light);
      scene.add(light.target);
      if (intensity > 2) {
        light.castShadow = true;
        light.shadow.mapSize.set(2048, 2048);
        const c = light.shadow.camera;
        c.near = 100;
        c.far = 2000;
        c.left = -600;
        c.right = 600;
        c.top = 600;
        c.bottom = -600;
        light.shadow.bias = -0.0006;
        light.shadow.normalBias = 0.6;
      }
    }
    scene.add(new THREE.HemisphereLight(0xffffff, 0xd8d8d2, 0.75));

    // ---- camera path -----------------------------------------------------
    /* Catmull-Rom through the stops rather than straight lerps: the camera arcs
       between zones the way a drone would, and the knots land exactly on each
       framing so a stop is still the shot that was checked in Blender. */
    const path = new THREE.CatmullRomCurve3(STOPS.map((s) => vec(s.position)), false, "catmullrom", 0.4);
    const look = new THREE.CatmullRomCurve3(STOPS.map((s) => vec(s.target)), false, "catmullrom", 0.4);

    const pos = new THREE.Vector3();
    const aim = new THREE.Vector3();

    function applyCamera(p: number) {
      const { u, i, moved } = stopParam(p);
      path.getPoint(u, pos);
      look.getPoint(u, aim);
      camera.position.copy(pos);
      camera.lookAt(aim);
      const a = STOPS[i].fov;
      const b = STOPS[Math.min(i + 1, STOPS.length - 1)].fov;
      camera.fov = a + (b - a) * moved;
      camera.updateProjectionMatrix();
    }

    // ---- load ------------------------------------------------------------
    const draco = new DRACOLoader();
    draco.setDecoderPath("/draco/");
    const loader = new GLTFLoader();
    loader.setDRACOLoader(draco);

    let disposed = false;
    const animated: Record<string, THREE.Object3D> = {};
    let roofRestY = 0;

    loader.load(
      "/scene/nomad-scene.glb",
      (gltf) => {
        if (disposed) {
          return;
        }
        gltf.scene.traverse((o) => {
          if ((o as THREE.Mesh).isMesh) {
            o.castShadow = true;
            o.receiveShadow = true;
          }
          /* Underscores, not dots. GLTFLoader runs every node name through
             PropertyBinding.sanitizeNodeName, which strips "." outright — so a
             pivot exported as anim.roof.ict arrives here called animroofict and
             every lookup below silently misses. */
          if (o.name.startsWith("anim_")) animated[o.name] = o;
        });

        const roof = animated[ROOF];
        if (roof) roofRestY = roof.position.y;

        /* A missing pivot is otherwise invisible: the scene renders perfectly and
           simply never moves. Say so rather than let it pass. */
        const missing = ANIMATED_NODES.filter((n) => !animated[n]);
        if (missing.length && process.env.NODE_ENV !== "production") {
          console.warn(
            `[ServicesStage] missing animated nodes: ${missing.join(", ")}. Found: ${
              Object.keys(animated).join(", ") || "none"
            }. Rebuild with scene/build_scene.py.`
          );
        }

        scene.add(gltf.scene);
        host.dataset.ready = "true";
      },
      undefined,
      () => {
        /* Missing, truncated, or undecodable — the loop would otherwise keep rendering
           an empty scene forever. Switching sets the effect's deps, so the cleanup
           below tears the renderer down on the way out. */
        if (disposed) return;
        setFallback(true);
      }
    );

    // ---- resize ----------------------------------------------------------
    const resize = () => {
      const { clientWidth: w, clientHeight: h } = host;
      renderer.setSize(w, h, false);
      camera.aspect = w / h;
      camera.updateProjectionMatrix();
    };
    resize();
    const ro = new ResizeObserver(resize);
    ro.observe(host);

    // ---- frame loop ------------------------------------------------------
    const clock = new THREE.Clock();
    let raf = 0;

    const frame = () => {
      raf = requestAnimationFrame(frame);
      const t = clock.getElapsedTime();
      const p = progress.current;
      applyCamera(p);

      /* Idle motion only near the camera. Animating all five zones at once is what
         made the old board feel busy — and it costs frames for detail nobody can
         resolve from three zones away.

         Proximity comes from the camera's own path parameter rather than the
         discrete zone index, so a part starts moving as the camera arrives instead
         of snapping on at the moment the copy swaps. */
      const { u } = stopParam(p);

      const roof = animated[ROOF];
      if (roof) {
        const open = nearStop(u, STOP_ICT);
        roof.position.y += (roofRestY + open * ROOF_LIFT - roof.position.y) * 0.07;
        // only hide it once it is comfortably out of frame, or it pops
        roof.visible = roof.position.y - roofRestY < ROOF_LIFT - 2;
      }

      if (nearStop(u, STOP_ENERGY) > 0) {
        TURBINES.forEach((name, i) => {
          const hub = animated[name];
          if (hub) hub.rotation.x = t * (0.5 + i * 0.12);
        });
        const beam = animated[PUMP];
        if (beam) beam.rotation.z = Math.sin(t * 1.5) * 0.22;
      }

      if (nearStop(u, STOP_ENGINEERING) > 0) {
        const jib = animated[CRANE];
        if (jib) jib.rotation.y = Math.sin(t * 0.16) * 0.5;
      }

      renderer.render(scene, camera);
    };

    if (reduced) {
      /* No loop at all: park on the stop and repaint only when it changes. The GLB
         still loads, so the page is not empty — it just does not move. */
      const paint = () => {
        applyCamera(progress.current);
        renderer.render(scene, camera);
      };
      const id = window.setInterval(paint, 400);
      return () => {
        disposed = true;
        window.clearInterval(id);
        ro.disconnect();
        renderer.dispose();
        draco.dispose();
        host.replaceChildren();
      };
    }

    raf = requestAnimationFrame(frame);

    return () => {
      disposed = true;
      cancelAnimationFrame(raf);
      ro.disconnect();
      scene.traverse((o) => {
        const m = o as THREE.Mesh;
        if (m.isMesh) {
          m.geometry?.dispose();
          const mat = m.material;
          if (Array.isArray(mat)) mat.forEach((x) => x.dispose());
          else mat?.dispose();
        }
      });
      renderer.dispose();
      draco.dispose();
      host.replaceChildren();
    };
  }, [progress, fallback]);

  if (fallback) return <ServicesScene active={active} />;

  return <div ref={mount} className="svc-stage" aria-hidden="true" />;
}
